[20기 최준식 전현수] Product List View 생성
wecode-bootcamp-korea/20-1st-KokoaFriendsGolf-backend pull request #11
Opened 2021-05-17 07:27 UTC by jeonhs2482

## 수정 사항 간략한 한줄 요약
- ProductListView 추가
		 
## 수정 사항들 자세한 내용
- 쿼리 파라미터로 카테고리, 서브카테고리, 캐릭터의 이름을 받아 필터링 하도록 처리
ex) /products?cname=아이맥 ex2) /products?cname=춘삼이

- 쿼리 파라미터로 PRICE, RECENT, LIKE 를 받아 정렬 하도록 처리
ex) /products?cname=아이맥&orderBy=PRICE

- 쿼리 파라미터 key값에 잘못된 정보 입력 시 전체 상품 필터링 되도록 처리
ex) /products?cccname=아이맥 <-- 전체상품 필터링

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-18 08:58 UTC, jeonhs2482 commented
conflict 해결했습니다~

2021-05-19 10:07 UTC, Kang-kyunghun requested changes

2021-05-19 10:07 UTC, Kang-kyunghun commented on products/views.py
> +        offset           = int(request.GET.get('offset')) if request.GET.get('offset') else None
.get의 default가 None이여서 뒤에 if절은 제거하셔도 될 것 같아요

2021-05-19 10:07 UTC, Kang-kyunghun commented on products/views.py
> +        products         = Product.objects.none()
none()을 사용한 이유를 코멘트로 남겨주세요.

2021-05-19 10:07 UTC, Kang-kyunghun commented on products/views.py
> +            products = sorted(products, key = lambda product: product.like_users.count())
order_by 부분은 지난번 구두로 말씀 드린대로 바꿔보세요.

2021-05-19 10:07 UTC, Kang-kyunghun commented on products/views.py
> +                products = products[offset:]
limit와 offset의 default 값을 미리 정해 주면 1번의 if만 있어도 될지 않을까요?   default 값은 위에서 .get으로 가져오는 부분에서 정해줄 수 있겠죠?
예를 들어 프론트에서 limit와 offset을 주지 않는다면 무조건 20개씩 1페이지 이런식으로요

2021-05-19 10:41 UTC, jeonhs2482 commented on products/views.py
> +        offset           = int(request.GET.get('offset')) if request.GET.get('offset') else None
request에서 limit 값이 들어올 때 문자형식으로 들어오기 때문에 int형으로 변환을 해주어야 하는데, int(request.GET.get('limit')) 만 사용하게 되면 None이 들어오게 될 경우 int형으로 변환이 되지 않고 타입에러가 발생하여 if절 까지 사용하여야 할 것 같습니다ㅜ

2021-05-19 10:48 UTC, jeonhs2482 commented on products/views.py
> +        products         = Product.objects.none()
아래에서 cname에 이상한 값이 들어와서 products가 빈 리스트가 되게되면, order_by 부분에서 에러가 발생하여, products에 빈 쿼리셋을 할당하여 에러가 나지 않도록 하기 위해 사용하였습니다.

2021-05-19 10:51 UTC, jeonhs2482 commented on products/views.py
> +                products = products[offset:]
네 수정해보겠습니다 ~

2021-05-19 10:52 UTC, jeonhs2482 commented on products/views.py
> +            products = sorted(products, key = lambda product: product.like_users.count())
구두로 말씀해 주신 내용이 정확히 기억이나질 않습니다..ㅜㅜ

2021-05-19 11:36 UTC, jeonhs2482 commented on products/views.py
> +        products         = Product.objects.none()
아래에서 cname에 이상한 값이 들어와서 products가 빈 리스트가 되게 되면, order_by 부분에서 에러가 발생하여, products에 빈 쿼리셋을 할당하여 에러가 나지 않도록 하기 위해 사용하였습니다.

2021-05-20 10:40 UTC, jeonhs2482 commented on products/views.py
> +            products = sorted(products, key = lambda product: product.like_users.count())
수정했습니다~

2021-05-20 11:36 UTC, Kang-kyunghun commented
고생 많으셨습니다~~!!!1

2021-05-20 11:36 UTC, merged